### ISSUE TITLE
Gem name does not follow ruby idioms

### ISSUE THREAD

**Issue by soulcutter** [tablexi/concrete_holidays#4]
Typically a gem named `foo-bar` will give you a `require "foo/bar"` syntax, and a `foo_bar` gem will give you `require "foo_bar"`.  E.g. `rspec-core` has `"rspec/core"` and `rspec-collection_matchers` has `"rspec/collection_matchers"`.

I would propose renaming this gem, or namespacing it under `concrete/` / `Concrete::`

**Comment by mlineen** [comment]
I think the more proper thing to do would be to call it concrete_holidays per http://guides.rubygems.org/name-your-gem/

**Comment by ahorner** [comment]
:+1: to `concrete_holidays`

**Comment by mlineen** [comment]
renamed
